<?php 
     $title         =$this->formText('title',$this->arrParam['title'],array('class'=>'txttextbox'));
     $published 	=$this->formRadio('published',0,null,array('0'=>'No','1'=>'Yes'), ' ');
     $order         =$this->formText('order',$this->arrParam['order'],array('class'=>'txttextbox')); 
?>
<div>
<form name="appForm" method="post" action="" id="appForm">
<?php echo $this->render('/tags/include/toolbar.php');?>
<?php 
     if (empty($this->error)==FALSE)
         {
           echo '<h2 class="error">'.$this->error.'</h2>'	;
         }
  ?>
  <table class="tbl_content" width="99%" cellspacing="0" cellpadding="4" border="0">
     <tr>
        <td class="left_lable">Title</td>
        <td class="right_lable"><?php echo $title;?></td>
     </tr>
      <tr>
        <td class="left_lable">Introtext</td>
        <td class="right_lable">
         <textarea name=introtext id=introtext class=txttextbox /></textarea>
			<script type="text/javascript">
             var editor = CKEDITOR.replace( 'introtext',{
            uiColor : '#9AB8F3',
            language:'vi',
            skin:'v2',
            width:'98%',
            heigth:'400px',
            filebrowserImageBrowseUrl : '<?php echo JURI."/ckfinder/ckfinder.html?Type=Images";?>',
            filebrowserFlashBrowseUrl : '<?php echo JURI."/ckfinder/ckfinder.html?Type=Flash";?>',
			filebrowserImageUploadUrl : 'ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images',
			filebrowserFlashUploadUrl : 'ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash',
			 	
            toolbar:[
            ['Source','-','Save','NewPage','Preview','-','Templates'],
            ['Cut','Copy','Paste','PasteText','PasteFromWord','-','Print'],
            ['Undo','Redo','-','Find','Replace','-','SelectAll','RemoveFormat'],
            ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton', 'HiddenField'],
            ['Bold','Italic','Underline','Strike','-','Subscript','Superscript'],
            ['NumberedList','BulletedList','-','Outdent','Indent','Blockquote','CreateDiv'],
            ['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],
            ['Link','Unlink','Anchor'],
            ['Image','Flash','Table','HorizontalRule','Smiley','SpecialChar','PageBreak'],
            ['Styles','Format','Font','FontSize'],
            ['TextColor','BGColor'],
            ['Maximize', 'ShowBlocks','-','About']
            ]
        });		
        </script>
       </td>
       
     </tr>
     
      
     <tr>
        <td class="left_lable">Published</td>
        <td class="right_lable"><?php echo $published;?></td>
     </tr>  
     <tr>
        <td class="left_lable">Order</td>
        <td class="right_lable"><?php echo $order; ?></td>
      </tr>
     

  </table>
  <input type="hidden" name="key" id="id" value="add"> 
</form>
</div>