<?php 
     
     $title         =$this->formText('title',$this->data['0']['title'],array('class'=>'txttextbox'));
     $type          =$this->formText('email',$this->data['0']['email'],array('class'=>'txttextbox'));
     
?>

<div>
<form name="appForm" method="post" action="" id="appForm">
<?php echo $this->render('/config/include/toolbar.php');?>
  <table class="tbl_content" width="99%" cellspacing="0" cellpadding="4" border="0">
     <tr>
        <td class="left_lable">Website Title</td>
        <td class="right_lable"><?php echo $title;?></td>
     </tr>
     <tr>
        <td class="left_lable">Email Contact</td>
        <td class="right_lable">
            <?php echo $type; ?>
         </td>
      <tr>
        <td class="left_lable">Description</td>
        <td class="right_lable">
         <textarea name=introtext id=introtext class=txttextbox /><?php echo $this->data['0']['contact']; ?></textarea>
			<script type="text/javascript">
        var editor = CKEDITOR.replace( 'introtext',{
            uiColor : '#9AB8F3',
            language:'vi',
            skin:'office2003',
            width:'850px',
            filebrowserImageBrowseUrl : '<?php echo JURI."/ckfinder/ckfinder.html?Type=Images";?>',
            filebrowserFlashBrowseUrl : '<?php echo JURI."/ckfinder/ckfinder.html?Type=Flash";?>',
			filebrowserImageUploadUrl : 'ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images',
			filebrowserFlashUploadUrl : 'ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash',
			 	
            toolbar:[
            ['Source','-','Save','NewPage','Preview','-','Templates'],
            ['Cut','Copy','Paste','PasteText','PasteFromWord','-','Print'],
            ['Undo','Redo','-','Find','Replace','-','SelectAll','RemoveFormat'],
            ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton', 'HiddenField'],
            ['Bold','Italic','Underline','Strike','-','Subscript','Superscript'],
            ['NumberedList','BulletedList','-','Outdent','Indent','Blockquote','CreateDiv'],
            ['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],
            ['Link','Unlink','Anchor'],
            ['Image','Flash','Table','HorizontalRule','Smiley','SpecialChar','PageBreak'],
            ['Styles','Format','Font','FontSize'],
            ['TextColor','BGColor'],
            ['Maximize', 'ShowBlocks','-','About']
            ]
        });		
        </script>
       </td>
       
     </tr>
    
   
  </table>
  <input type="hidden" name="key" id="id" value="add">

</form>
</div>