<?php   $error=$this->error;?>
<div class="padding">
<div class="clr"></div>
  <div id="element-box" class="login">
    <div class="t">
     <div class="t">
       <div class="t"></div>
     </div>
   </div>
<div class="m wbg">
   <h1>ZKiwi | Administration Login</h1>
     <div id="section-box">
        <div class="t">
           <div class="t">
             <div class="t"></div>
           </div>
        </div>
      <div class="m">
        <form id="form-login" method="post"" action="">
			<fieldset class="loginform">
				<label id="mod-login-username-lbl" for="mod-login-username">User Name</label>
				<input id="mod-login-username" class="inputbox" type="text" size="15" name="username">
				<label id="mod-login-password-lbl" for="mod-login-password">Password</label>
				<input id="mod-login-password" class="inputbox" type="password" size="15" name="passwd">
			     
	            
                <div class="clr"></div>
                <p class="error"><?php   echo $error; ?></p>	
                <input type="submit" value="login" id="login_button" name="login">
            </fieldset>
         </form>
     <div class="clr"></div>
  </div>
<div class="b">
         <div class="b">
             <div class="b"></div>
         </div>
</div>
</div>

<div id="lock">
        <img src="images/j_login_lock.jpg">
        <br><a href="<?php echo JURI; ?>" style="margin-left: 45px;">Go to home </a>
</div>
<div class="clr"></div>
</div>
<div class="b">
     <div class="b">
          <div class="b"></div>
      </div>
   </div>
</div>

</div>

